/*!
 * downstream-electron,0.4.0,2020-04-21 10:48:36.851,castlabs GmbH
 * 
 * Copyright (C) 2017 Castlabs GmbH.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
!function(e,t){if("object"==typeof exports&&"object"==typeof module)module.exports=t(require("express"),require("cors"));else if("function"==typeof define&&define.amd)define(["express","cors"],t);else{var n="object"==typeof exports?t(require("express"),require("cors")):t(e.express,e.cors);for(var r in n)("object"==typeof exports?exports:e)[r]=n[r]}}(global,function(n,r){return u={},o.m=s={108:function(e,t,n){e.exports=n(109)},109:function(e,t,n){var r=n(110),o=n(111);!function(){process.send({cmd:"log",log:"Starting HTTP server"});var t=r();t.use(o()),process.on("message",function(e){"init"===e.cmd&&(n(112)(t,e.routeName),t.listen(e.port,function(){process.send({cmd:"listening_port",port:e.port})}))})}()},110:function(e,t){e.exports=n},111:function(e,t){e.exports=r},112:function(e,t,n){"use strict";var r=n(3);function i(e,n){r.stat(e,function(e,t){e?n(!1):n(!0,t.size)})}var s=0,u={};function f(e,t){var n=function(){var e=(new Date).getTime();return++s+"-"+e}(),r=new Promise(function(e,t){u[n]={resolve:e,reject:t}}),o={};return o.requestId=n,o.cmd=e,o.args=t,process.send(o),r}function o(e){var t,n=e.requestId,r=e.error,o=e.result,s=u[n+""];s&&("OK"===e.status?(t=o,s.resolve(t)):s.reject(r),delete u[n])}e.exports=function(e,t){var u={};process.on("message",o),e.get("/"+t+"/:id/*",function(n,r){function o(e){r.sendFile(e,{dotfiles:"deny"},function(e){e&&e.status&&(delete u[s],r.status(e.status).end())})}function t(e){if(e&&"FINISHED"===e.status){var t=e.folder+"/"+s+"/"+n.params[0];i(t,function(e){if(!e)return delete u[s],r.status(404).end();o(t)})}else!function(e){var t=e+"/"+s+"/"+n.params[0];i(t,function(e){e?f("is_downloading",{manifest:s,file:t}).then(function(){o(t)}).catch(function(){return r.status(404).end()}):f("perform_seek",{manifest:s,file:t}).then(function(){o(t)}).catch(function(){return r.status(404).end()})})}(e.folder)}var s=n.params.id;u[s]?t(u[s]):f("get_info",{manifest:s}).then(function(e){u[s]=e,t(u[s])}).catch(function(){return delete u[s],r.status(404).send("Cannot find manifest")})})}},3:function(e,t){e.exports=require("fs")}},o.c=u,o.d=function(e,t,n){o.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},o.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},o.t=function(t,e){if(1&e&&(t=o(t)),8&e)return t;if(4&e&&"object"==typeof t&&t&&t.__esModule)return t;var n=Object.create(null);if(o.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:t}),2&e&&"string"!=typeof t)for(var r in t)o.d(n,r,function(e){return t[e]}.bind(null,r));return n},o.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return o.d(t,"a",t),t},o.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},o.p="",o(o.s=108);function o(e){if(u[e])return u[e].exports;var t=u[e]={i:e,l:!1,exports:{}};return s[e].call(t.exports,t,t.exports,o),t.l=!0,t.exports}var s,u});